server:
    port: 8761

eureka:
    client:
        registerWithEureka: false
        fetchRegistry: false
    server:
        enable-self-preservation: false
        waitTimeInMsWhenSyncEmpty: 0
        eviction-interval-timer-in-ms: 5000
